### ISSUE TITLE
Errors in unit tests

### ISSUE THREAD

**Issue by kanishkarj** [nnetworth/nnetworth.com#12]
There are Errors in the unit tests. I have looked into it, the errors are in the sass files. someone, please look into it.

**Comment by andreidolhescu** [comment]
Hi @kanishkarj , 
I've created a PR ^

**Comment by kienpham2000** [comment]
awesome works guys! repo all passing now. Thank you!

**Comment by kienpham2000** [comment]
@andreidolhescu invited you to the org, please go here to confirm: https://github.com/nnetworth/
